"""empty message

Revision ID: 4436616b48ab
Revises:
Create Date: 2021-07-26 14:40:30.078220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4436616b48ab"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token",
        sa.Column("id", sa.Numeric(precision=80), nullable=False),
        sa.Column("symbol", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("decimals", sa.Integer(), nullable=False),
        sa.Column("trade_volume", sa.Numeric(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "burn",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("block", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("token_id", sa.Numeric(precision=80), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(["token_id"], ["token.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_burn_timestamp"), "burn", ["timestamp"], unique=False)
    op.create_table(
        "buyback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("block", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("token_id", sa.Numeric(precision=80), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(["token_id"], ["token.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_buyback_timestamp"), "buyback", ["timestamp"], unique=False
    )
    op.create_table(
        "pair",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_token_id", sa.Numeric(precision=80), nullable=False),
        sa.Column("to_token_id", sa.Numeric(precision=80), nullable=False),
        sa.Column("from_volume", sa.Numeric(), nullable=True),
        sa.Column("to_volume", sa.Numeric(), nullable=True),
        sa.ForeignKeyConstraint(["from_token_id"], ["token.id"]),
        sa.ForeignKeyConstraint(["to_token_id"], ["token.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "swap",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("txid", sa.Numeric(precision=80), nullable=True),
        sa.Column("block", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("xor_fee", sa.Numeric(precision=20), nullable=False),
        sa.Column("pair_id", sa.Integer(), nullable=False),
        sa.Column("from_amount", sa.Numeric(), nullable=False),
        sa.Column("to_amount", sa.Numeric(), nullable=False),
        sa.Column("filter_mode", sa.String(length=32), nullable=False),
        sa.Column("swap_fee_amount", sa.Numeric(precision=21), nullable=True),
        sa.ForeignKeyConstraint(["pair_id"], ["pair.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_swap_pair_timestamp_desc",
        "swap",
        ["pair_id", sa.text("timestamp DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_swap_timestamp"), "swap", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_swap_timestamp"), table_name="swap")
    op.drop_index("idx_swap_pair_timestamp_desc", table_name="swap")
    op.drop_table("swap")
    op.drop_table("pair")
    op.drop_index(op.f("ix_buyback_timestamp"), table_name="buyback")
    op.drop_table("buyback")
    op.drop_index(op.f("ix_burn_timestamp"), table_name="burn")
    op.drop_table("burn")
    op.drop_table("token")
    # ### end Alembic commands ###
