"""empty message

Revision ID: 4957211c454a
Revises: 4436616b48ab
Create Date: 2021-08-12 13:18:48.555509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4957211c454a'
down_revision = '4436616b48ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('swap', 'swap_fee_amount',
               existing_type=sa.NUMERIC(precision=21, scale=0),
               type_=sa.Numeric(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('swap', 'swap_fee_amount',
               existing_type=sa.Numeric(),
               type_=sa.NUMERIC(precision=21, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###
