"""empty message

Revision ID: 5a8dabe721fa
Revises: 
Create Date: 2021-06-17 17:40:48.160462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8dabe721fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=66), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('precision', sa.Integer(), nullable=False),
    sa.Column('trade_volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('pair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token0_id', sa.Integer(), nullable=False),
    sa.Column('token1_id', sa.Integer(), nullable=False),
    sa.Column('token0_volume', sa.Float(), nullable=True),
    sa.Column('token1_volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['token0_id'], ['token.id'], ),
    sa.ForeignKeyConstraint(['token1_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swap',
    sa.Column('id', sa.Numeric(precision=20), nullable=False),
    sa.Column('block', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('xor_fee', sa.Numeric(precision=20), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('token0_amount', sa.Numeric(precision=33), nullable=False),
    sa.Column('token1_amount', sa.Numeric(precision=33), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('filter_mode', sa.String(length=32), nullable=False),
    sa.Column('swap_fee_amount', sa.Numeric(precision=21), nullable=True),
    sa.ForeignKeyConstraint(['pair_id'], ['pair.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_swap_pair_timestamp_desc', 'swap', ['pair_id', sa.text('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_swap_timestamp'), 'swap', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swap_timestamp'), table_name='swap')
    op.drop_index('idx_swap_pair_timestamp_desc', table_name='swap')
    op.drop_table('swap')
    op.drop_table('pair')
    op.drop_table('token')
    # ### end Alembic commands ###
