"""empty message

Revision ID: 8dd169389646
Revises: 29c9ff4e6926
Create Date: 2021-07-02 11:44:43.666306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8dd169389646"
down_revision = "29c9ff4e6926"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pair", "token1_volume")
    op.drop_column("pair", "token0_volume")
    op.drop_column("token", "trade_volume")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "token",
        sa.Column(
            "trade_volume",
            sa.NUMERIC(precision=34, scale=0),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "pair",
        sa.Column(
            "token0_volume",
            sa.NUMERIC(precision=34, scale=0),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "pair",
        sa.Column(
            "token1_volume",
            sa.NUMERIC(precision=34, scale=0),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
