"""Remove swap amount limits

Revision ID: b95ad8023ef8
Revises: e3e1a25cae68
Create Date: 2021-07-15 13:32:24.377427

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b95ad8023ef8"
down_revision = "e3e1a25cae68"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "swap",
        "token0_amount",
        existing_type=sa.Numeric(33),
        type_=sa.Numeric(),
        existing_nullable=False,
    )
    op.alter_column(
        "swap",
        "token1_amount",
        existing_type=sa.Numeric(33),
        type_=sa.Numeric(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "swap",
        "token1_amount",
        existing_type=sa.Numeric(),
        type_=sa.Numeric(33),
        existing_nullable=False,
    )
    op.alter_column(
        "swap",
        "token0_amount",
        existing_type=sa.Numeric(),
        type_=sa.Numeric(33),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
