"""empty message

Revision ID: e3e1a25cae68
Revises: 8dd169389646
Create Date: 2021-07-02 11:47:57.854369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e3e1a25cae68"
down_revision = "8dd169389646"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pair", sa.Column("token0_volume", sa.Numeric(), nullable=True))
    op.add_column("pair", sa.Column("token1_volume", sa.Numeric(), nullable=True))
    op.add_column("token", sa.Column("trade_volume", sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("token", "trade_volume")
    op.drop_column("pair", "token1_volume")
    op.drop_column("pair", "token0_volume")
    # ### end Alembic commands ###
